# Notebook: python basics 
[Bioimage analysis]('https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/intro.html')

Prepare env
> mamba create --name devbio-napari-env python=3.9 devbio-napari -c conda-forge

Test env
> conda activate devbio-napari-env

Test graphics card is installed:

In [1]:
import pyclesperanto_prototype as cle

In [2]:
cle.get_device

<function pyclesperanto_prototype._tier0._device.get_device() -> pyclesperanto_prototype._tier0._device.Device>

**f-strings exercise**: Marie Curie’s name and birthdate are stored in variables. Concatenate them in one string variable and print it out. The output should be “Marie Curie, * 7 November 1867”

In [3]:
first_name = "Marie"
last_name = "Curie"

birthday_day = 7
birthday_month = "November"
birthday_year = 1867

print(f'"{first_name} {last_name}, *{birthday_day} {birthday_month} {birthday_year}"')

"Marie Curie, *7 November 1867"


**Lists exercise:** Assume you did measurements on multiple days. Compute average measurement of this week?

In [4]:
measurements_monday = [2.3, 3.1, 5.6]
measurements_tuesday = [1.8, 7.0]
measurements_wednesday = [4.5, 1.5, 6.4, 3.2]
measurements_thursday = [1.9, 2.0]
measurements_friday = [4.4]

In [5]:
total = sum(
    measurements_friday
    + measurements_monday
    + measurements_thursday
    + measurements_tuesday
    + measurements_wednesday
)
len = len(
    measurements_friday
    + measurements_monday
    + measurements_thursday
    + measurements_tuesday
    + measurements_wednesday
)

In [6]:
average = total / len
print(average)

3.641666666666667


***Cropping lists exercise:*** Please select the three numbers 23, 9 and 78 from data using a single python command similar to the commands shown above.

In [7]:
data = [34, 0, 65, 23, 51, 9, 50, 78, 34, 100]

In [8]:
data[3:8:2]

[23, 9, 78]

***Sorting lists exercise:***
Find out the median of these two lists of numbers

In [9]:
data1 = [6, 4, 3, 4, 8, 10]
data2 = [6, 4, 3, 4, 8, 10, 8]

In [10]:
import numpy as np

In [11]:
print("median of two arrays : ", np.median(data1 + data2))

median of two arrays :  6.0


***Masking Arrays exercise:***
- Create a new mask for all measurements below 20.

- Apply the mask to retrieve a new array with numbers below 20.

- Compute the average of all numbers below 20.

In [12]:
import numpy

measurements = numpy.asarray([1, 17, 25, 3, 5, 26, 12])
measurements

array([ 1, 17, 25,  3,  5, 26, 12])

In [13]:
# mask for measurements below 20
mask = measurements < 20
mask

array([ True,  True, False,  True,  True, False,  True])

In [14]:
# apply mask to retrieve new array with numbers below 20
measurements2 = measurements[mask]
measurements2

array([ 1, 17,  3,  5, 12])

In [15]:
# average of all numbers below 20
np.average(measurements2)

7.6

***Dictionaries exercise:*** *You just measured the radius of three circles. Write them into a table and add a column with corresponding circlea area measurements.*

In [16]:
import pandas as pd

In [17]:
r1 = 12
r2 = 8
r3 = 15

In [18]:
id = ["r1", "r2", "r3"]
radius = [r1, r2, r3]

In [19]:
circles = pd.DataFrame({"id": id, "radius": radius})
circles

id  radius
0  r1      12
1  r2       8
2  r3      15

In [21]:
area = []
pi = 3.14
id = 2

for i in radius:
    area.append((i**2) * pi)

In [22]:
area

[452.16, 200.96, 706.5]

In [24]:
data_table = pd.DataFrame({"id": id, "radius": radius, "area": area})
print(data_table)

   id  radius    area
0   2      12  452.16
1   2       8  200.96
2   2      15  706.50


**Conditions exercise:** Write python code that prints out the daytime, e.g. “morning”, “noon”, “afternoon”, “evening” and “night” depending on a given time.

In [26]:
# it's 12:15
time_hours = 12
time_minutes = 15

In [27]:
if time_hours < 12:
    print("morning")
elif time_hours == 12:
    print("noon")
elif (time_hours > 12) & (time_hours < 5):
    print("afternoon")
elif (time_hours >= 5) & (time_hours < 8):
    print("evening")
else:
    print("night")

noon


**Loops exercise 1:**

- Assume you have a list of filenames and you want to do something with them, for example print them out. Program a for loop which prints out all file names which end with “tif”.

In [28]:
file_names = ["dataset1.tif", "dataset2.tif", "summary.csv", "readme.md", "blobs.tif"]

In [29]:
for file in file_names:
    # select files ending in .tif
    if file.endswith(".tif"):
        print(file)

dataset1.tif
dataset2.tif
blobs.tif


**Loops exercise 2:**

-Assume you have a list of circle radii. Make a table (dictionary) with two columns: radius and area.

In [30]:
radii = [3, 15, 67, 33, 12, 8, 12, 9, 22]

In [34]:
area = []
pi = 3.14

for radius in radii:
    area.append((radius**2) * pi)

circle = [{"radii": radii, "area": area}]

circle

[{'radii': [3, 15, 67, 33, 12, 8, 12, 9, 22],
  'area': [28.26,
   706.5,
   14095.460000000001,
   3419.46,
   452.16,
   200.96,
   452.16,
   254.34,
   1519.76]}]

**Functions**

Documenting functions using a doc string:

In [35]:
def square(number):
    """
    Squares a number by multiplying it with itself and returns its result.
    """

    return number * number

In [36]:
# Can access/read doc string of function like this:
print(square.__doc__)


    Squares a number by multiplying it with itself and returns its result.
    


In [37]:
# show the docstring shown side-by-side in your notebook:
?square

Signature: square(number)
Docstring: Squares a number by multiplying it with itself and returns its result.
File:      c:\users\jaz\appdata\local\temp\ipykernel_2168\2780286315.py
Type:      function

**Functions exercise:**
- Write a function that takes two parameters: number_of_points_in_exam and number_of_total_points_in_exam and returns a grade from 1 to 5. Students with > 95% of the points get grade 1, above 80% they get grade 2, above 60% grade 3 and above 50% grade 4. Students with less than 50% get grade 5 and have to repeat the exam. Then, call the function for three students who had 15, 25 and 29 points in an exam with 30 total points.

In [39]:
number_of_points_in_exam = 8
number_of_total_points_in_exam = 10

percent_grade = (number_of_points_in_exam / number_of_total_points_in_exam) * 100

percent_grade

80.0

In [40]:
def percent_grade(number_of_points_in_exam, number_of_total_points_in_exam):
    """calculate grade percentage"""
    result = (number_of_points_in_exam / number_of_total_points_in_exam) * 100

    return result

In [51]:
percent_grade(9, 10)

90.0

In [50]:
calculated_grade = percent_grade(9, 10)


if calculated_grade > 95:
    print("Student grade 1")
elif (calculated_grade > 80) & (calculated_grade < 95):
    print("Student grade 2")
elif (calculated_grade > 60) & (calculated_grade < 80):
    print("Student grade 3")
elif (calculated_grade > 50) & (calculated_grade < 60):
    print("Student grade 4")
else:
    print("Repeat exam")

Student grade 2


In [58]:
calculated_grade = percent_grade(9, 10)


def print_grade(calculated_grade):
    """define categories for grade percentage"""
    if calculated_grade > 95:
        print("Student grade 1")
    elif (calculated_grade > 80) & (calculated_grade < 95):
        print("Student grade 2")
    elif (calculated_grade > 60) & (calculated_grade < 80):
        print("Student grade 3")
    elif (calculated_grade > 50) & (calculated_grade < 60):
        print("Student grade 4")
    else:
        print("Repeat exam")

In [59]:
calculated_grade = percent_grade(15, 30)
print_grade(calculated_grade)

Repeat exam
